### PR TITLE
Make program a lib

### PR DESCRIPTION
**Pull request by henriklovhaug**

### CODE REVIEW

**Comment by orhun** [comment]
ah, you beat me to it :) I was slowed by the number of treesitter dependencies :D

**Comment by orhun** [comment]
btw my PR at #150 allows enabling individual tree-sitter plugins instead of disabling all of them at once

**Comment by henriklovhaug** [comment]
Ah, I see. Smarter that way

**Comment by orhun** [comment]
Feel free to push to my PR or I can add your modifications from here to there :) Just lmk

**Comment by henriklovhaug** [comment]
Closed due to skill issue. (The other was better :P )

**Pull request closed without merging**
