### PR TITLE
Split into library and binary

### PR DESCRIPTION
**Pull request by erak**
It would be great to be able to use `md-tui` as a library and build own widgets around it.

This pull request:
- adds a folder `bin/` and moves all modules that are needed to build the binary to it
- moves the `TextComponent` widget implementation and render-related code to the module itself
- moves shared config code to own library module
- adds a library usage demo

### CODE REVIEW

**Comment by henriklovhaug** [comment]
Nice. I'll take a look at it later today

**Comment by henriklovhaug** [comment]
Seems like the `bin` folder was not added

**Comment by erak** [comment]
> Seems like the `bin` folder was not added. Bin is in `.gitignore` from a while back when I cross built for x86

Oh, sorry! Fixed :)

**Comment by henriklovhaug** [comment]
Isn't it sufficient to create a lib.rs file and do the `pub mod` there? Why move it outside of src?

**Comment by orhun** [comment]
> Isn't it sufficient to create a lib.rs file and do the pub mod there? Why move it outside of src?

That would work. We only need to change the `[[bin]]` directive in `Cargo.toml` I think.

Btw what is the status on this? I really need a markdown renderer widget and `md-tui` seems like the best one around.

@henriklovhaug would you be down to accept this PR with the suggested changes applied and conflicts resolved? I think I can submit another PR while including these changes since @erak doesn't seem to be around for a while.

LMK!

**Comment by henriklovhaug** [comment]
I can take a look at it.

**Comment by orhun** [comment]
I would also like to add feature flags for disabling some of the heavy dependencies (e.g. treesitter ones). Also, I realized some issues with the height calculation. I think I will submit a PR with all of those fixes :)

**Comment by henriklovhaug** [comment]
By all means submit a PR. I never made this with a library flow in mind. I created it because Glow couldn't follow links, so I see it's not too ergonomic to implement in you own TUI program.

**Pull request merged**
