### PR TITLE
feat(parser): highlight inline links

### LINKED ISSUE #156: Link colors
Currently link colors work when URLs are in the format `[Example](https://example.com)`

Would be great if links like `<https://example.com>` or even `https://example.com` had colors as well similar to [glow](https://github.com/charmbracelet/glow).

### PR DESCRIPTION
**Pull request by orhun**
closes #156

### CODE REVIEW

**Comment by henriklovhaug** [comment]
Good start, but it would be beneficial to treat it the same way as a wiki link.

See `parser.rs` around line 200

```rust
        MdParseEnum::Paragraph => {
            let leaf_nodes = get_leaf_nodes(parse_node);
            let mut words = Vec::new();
            for node in leaf_nodes {
                let word_type = WordType::from(node.kind());
                let mut content = node.content().to_owned();

                if node.kind() == MdParseEnum::WikiLink {
                    let comp = Word::new(content.clone(), WordType::LinkData);
                    words.push(comp);
                }

                if content.starts_with(' ') {
                    content.remove(0);
                    let comp = Word::new(" ".to_owned(), word_type);
                    words.push(comp);
                }
                words.push(Word::new(content, word_type));
            }
            if let Some(w) = words.first_mut() {
                w.set_content(w.content().trim_start().to_owned());
            }
            Component::TextComponent(TextComponent::new(TextNode::Paragraph, words))
        }
```

This will allow the link to be selectable and not just colourable.

**Comment by orhun** [comment]
Yeah, that'd be a good addition after I can make the parser correct :D

Right now the following file is recognized as `Paragraph` for some reason.

```md
<https://inline.com>
```

And it is not being rendered at all. 

Can you take a look at the pest file and let me know if I'm doing something wrong? 🤔

**Comment by henriklovhaug** [comment]
You can see some differences in PR #158

**Comment by orhun** [comment]
I was close! :D

**Pull request closed without merging**
