### PR TITLE
add nix flake

### PR DESCRIPTION
**Pull request by honnip**
This pr introduces the nix packaging and simple dev shell. 

This also allows `nix run github:henriklovhaug/md-tui` to run the package, which can be tested with `nix run github:honnip/md-tui` now.

### CODE REVIEW

**Comment by henriklovhaug** [comment]
Never used `nix` before, but I'll try it out. Should the lock file also be committed?

**Comment by honnip** [comment]
Yes, it's for reproducibility, but without it, it will display an annoying prompt I remember

**Comment by henriklovhaug** [comment]
Alright. Update changelog file, optionally include you name there, and I'll merge it in.

**Comment by henriklovhaug** [comment]
It should also be mentioned in the README

**Comment by honnip** [comment]
I've simply added a mention of flake because the way package is installed from flake depends on each user's environment. 

I committed changes on github web editor, and I couldn't find how to overwrite the history. Squash merge please.

**Pull request merged**
